// versiculo.js — publicado automaticamente todo dia via GitHub Actions
const admin = require('firebase-admin');

// ── VERSÍCULOS (365 — um por dia) ─────────────────────────────────────
const VERSICULOS = [
  { texto: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.", ref: "João 3:16" },
  { texto: "O Senhor é o meu pastor; nada me faltará.", ref: "Salmos 23:1" },
  { texto: "Tudo posso naquele que me fortalece.", ref: "Filipenses 4:13" },
  { texto: "Porque eu sei os planos que tenho para vocês, diz o Senhor, planos de fazê-los prosperar e não de causar dano, planos de dar a vocês esperança e um futuro.", ref: "Jeremias 29:11" },
  { texto: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento.", ref: "Provérbios 3:5" },
  { texto: "Sede fortes e corajosos. Não temais, nem vos assusteis diante deles; porque o Senhor, teu Deus, é o que vai contigo; não te deixará, nem te desamparará.", ref: "Deuteronômio 31:6" },
  { texto: "O Senhor te abençoe e te guarde; o Senhor faça resplandecer o seu rosto sobre ti e te conceda graça.", ref: "Números 6:24-25" },
  { texto: "Busquem, pois, em primeiro lugar o Reino de Deus e a sua justiça, e todas essas coisas lhes serão acrescentadas.", ref: "Mateus 6:33" },
  { texto: "Não vos conformeis com este século, mas transformai-vos pela renovação do vosso entendimento.", ref: "Romanos 12:2" },
  { texto: "Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai senão por mim.", ref: "João 14:6" },
  { texto: "Posso fazer tudo por meio daquele que me fortalece.", ref: "Filipenses 4:13" },
  { texto: "O Senhor é a minha luz e a minha salvação; a quem temerei?", ref: "Salmos 27:1" },
  { texto: "Alegrai-vos sempre no Senhor; outra vez digo: Alegrai-vos.", ref: "Filipenses 4:4" },
  { texto: "Porque o Senhor teu Deus está contigo por onde quer que andares.", ref: "Josué 1:9" },
  { texto: "O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha.", ref: "1 Coríntios 13:4" },
  { texto: "Deleita-te também no Senhor, e ele te concederá os desejos do teu coração.", ref: "Salmos 37:4" },
  { texto: "Nada façais por rivalidade ou vanglória, mas por humildade estimai os outros superiores a vós mesmos.", ref: "Filipenses 2:3" },
  { texto: "Pedi e dar-se-vos-á; buscai e achareis; batei e abrir-se-vos-á.", ref: "Mateus 7:7" },
  { texto: "Não andem ansiosos por coisa alguma, mas em tudo, pela oração e súplicas, com ação de graças, apresentem seus pedidos a Deus.", ref: "Filipenses 4:6" },
  { texto: "O coração alegre é um bom remédio, mas o espírito abatido seca os ossos.", ref: "Provérbios 17:22" },
  { texto: "Sede bons e compassivos uns para com os outros, perdoando-vos mutuamente, assim como Deus vos perdoou em Cristo.", ref: "Efésios 4:32" },
  { texto: "Porque onde estiverem dois ou três reunidos em meu nome, ali estou no meio deles.", ref: "Mateus 18:20" },
  { texto: "Honra a teu pai e a tua mãe, para que se prolonguem os teus dias na terra.", ref: "Êxodo 20:12" },
  { texto: "Que o Deus da esperança os encha de toda alegria e paz, por sua confiança nele.", ref: "Romanos 15:13" },
  { texto: "Acima de tudo, porém, revesti-vos do amor, que é o vínculo da perfeição.", ref: "Colossenses 3:14" },
  { texto: "Instrui o jovem no caminho em que deve andar; e até quando envelhecer não se desviará dele.", ref: "Provérbios 22:6" },
  { texto: "O Senhor está perto de todos os que o invocam, de todos os que o invocam em verdade.", ref: "Salmos 145:18" },
  { texto: "Não se turbe o vosso coração; credes em Deus, crede também em mim.", ref: "João 14:1" },
  { texto: "Portanto, se alguém está em Cristo, é nova criatura; as coisas velhas já passaram; eis que se fizeram novas.", ref: "2 Coríntios 5:17" },
  { texto: "E conhecereis a verdade, e a verdade vos libertará.", ref: "João 8:32" },
  { texto: "O Senhor é minha força e meu escudo; meu coração nele confia, e dele recebo ajuda.", ref: "Salmos 28:7" },
  { texto: "Amados, amemo-nos uns aos outros, porque o amor é de Deus.", ref: "1 João 4:7" },
  { texto: "Não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus.", ref: "Isaías 41:10" },
  { texto: "Porque de tal maneira amou Deus o mundo que deu o seu Filho unigênito.", ref: "João 3:16" },
  { texto: "Aguarda o Senhor; anima-te, e ele fortalecerá o teu coração.", ref: "Salmos 27:14" },
  { texto: "A fé é a certeza daquilo que esperamos e a prova das coisas que não vemos.", ref: "Hebreus 11:1" },
  { texto: "Porque Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio.", ref: "2 Timóteo 1:7" },
  { texto: "Sede fortes na fé, sabendo que os vossos irmãos, espalhados pelo mundo, passam pelos mesmos sofrimentos.", ref: "1 Pedro 5:9" },
  { texto: "Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco.", ref: "1 Tessalonicenses 5:18" },
  { texto: "O amor não faz mal ao próximo. Portanto, o amor é o cumprimento da lei.", ref: "Romanos 13:10" },
  { texto: "Mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias.", ref: "Isaías 40:31" },
  { texto: "Porque eu vivo, e vós também vivereis.", ref: "João 14:19" },
  { texto: "Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.", ref: "1 Pedro 5:7" },
  { texto: "Criou Deus o homem à sua imagem; à imagem de Deus o criou; homem e mulher os criou.", ref: "Gênesis 1:27" },
  { texto: "Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios.", ref: "Salmos 103:2" },
  { texto: "Se Deus é por nós, quem será contra nós?", ref: "Romanos 8:31" },
  { texto: "O Senhor te guardará de todo o mal; ele guardará a tua alma.", ref: "Salmos 121:7" },
  { texto: "Mas eu vos digo: Amai os vossos inimigos e orai pelos que vos perseguem.", ref: "Mateus 5:44" },
  { texto: "Toda a Escritura é divinamente inspirada e proveitosa para ensinar, para repreender, para corrigir.", ref: "2 Timóteo 3:16" },
  { texto: "Quem habita no esconderijo do Altíssimo, à sombra do Onipotente descansará.", ref: "Salmos 91:1" },
  { texto: "Jesus Cristo é o mesmo, ontem, hoje e eternamente.", ref: "Hebreus 13:8" },
  { texto: "Pois estou convencido de que nem morte nem vida... nos poderá separar do amor de Deus.", ref: "Romanos 8:38-39" },
  { texto: "Vinde a mim, todos os que estais cansados e sobrecarregados, e eu vos darei descanso.", ref: "Mateus 11:28" },
  { texto: "O Senhor é bom para todos, e as suas misericórdias estão sobre todas as suas obras.", ref: "Salmos 145:9" },
  { texto: "Ide por todo o mundo e pregai o evangelho a toda criatura.", ref: "Marcos 16:15" },
  { texto: "Ora, a fé sem obras é morta.", ref: "Tiago 2:26" },
  { texto: "A misericórdia do Senhor dura para sempre, e sua justiça permanece para sempre.", ref: "Salmos 103:17" },
  { texto: "Filho meu, não te esqueças dos meus ensinos, e o teu coração guarde os meus mandamentos.", ref: "Provérbios 3:1" },
  { texto: "Porque há esperança para a árvore: se for cortada, ainda se renovará.", ref: "Jó 14:7" },
  { texto: "Felizes os pacificadores, pois serão chamados filhos de Deus.", ref: "Mateus 5:9" },
  { texto: "Dai e ser-vos-á dado; boa medida, recalcada, sacudida e transbordante.", ref: "Lucas 6:38" },
  { texto: "A paz de Deus, que excede todo o entendimento, guardará os vossos corações.", ref: "Filipenses 4:7" },
  { texto: "Mas procurai primeiro o reino de Deus e a sua justiça.", ref: "Mateus 6:33" },
  { texto: "Louvai o Senhor, porque ele é bom; porque a sua misericórdia dura para sempre.", ref: "Salmos 107:1" },
  { texto: "A Palavra de Deus é viva, e eficaz, e mais cortante do que qualquer espada de dois gumes.", ref: "Hebreus 4:12" },
  { texto: "O meu auxílio vem do Senhor, que fez o céu e a terra.", ref: "Salmos 121:2" },
  { texto: "Quem anda em integridade anda seguro, mas quem perverte os seus caminhos será descoberto.", ref: "Provérbios 10:9" },
  { texto: "Não vos deixarei órfãos; voltarei para vós.", ref: "João 14:18" },
  { texto: "O justo viverá pela fé.", ref: "Romanos 1:17" },
  { texto: "Não te afastes desta lei, para que sejas próspero em tudo o que fizeres.", ref: "Josué 1:8" },
  { texto: "Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei.", ref: "Apocalipse 3:20" },
  { texto: "Porque onde estiver o vosso tesouro, aí estará também o vosso coração.", ref: "Mateus 6:21" },
  { texto: "Sede uns para com os outros benignos e compassivos, perdoando-vos uns aos outros.", ref: "Efésios 4:32" },
  { texto: "O homem não viverá só de pão, mas de toda palavra que sai da boca de Deus.", ref: "Mateus 4:4" },
  { texto: "E sabemos que todas as coisas contribuem para o bem daqueles que amam a Deus.", ref: "Romanos 8:28" },
  { texto: "O princípio da sabedoria é o temor do Senhor.", ref: "Provérbios 9:10" },
  { texto: "Esforça-te e tem bom ânimo; não temas, nem te espantes.", ref: "Josué 1:9" },
  { texto: "Mas a graça do nosso Senhor Jesus Cristo seja com todos vós. Amém.", ref: "Apocalipse 22:21" },
  { texto: "Cria em mim, ó Deus, um coração puro, e renova dentro de mim um espírito reto.", ref: "Salmos 51:10" },
  { texto: "Nisto conhecerão todos que sois meus discípulos, se tiverdes amor uns aos outros.", ref: "João 13:35" },
  { texto: "Bem-aventurado o homem que acha a sabedoria, e o homem que adquire o conhecimento.", ref: "Provérbios 3:13" },
  { texto: "Portanto, sejam imitadores de Deus, como filhos amados.", ref: "Efésios 5:1" },
  { texto: "O Senhor é a minha força e o meu cântico, e se tornou a minha salvação.", ref: "Êxodo 15:2" },
  { texto: "A graça do Senhor Jesus Cristo seja com o vosso espírito.", ref: "Filipenses 4:23" },
  { texto: "Os teus olhos viram o meu embrião; no teu livro foram escritos todos os meus dias.", ref: "Salmos 139:16" },
  { texto: "Ora, o Senhor é o Espírito, e onde está o Espírito do Senhor, aí há liberdade.", ref: "2 Coríntios 3:17" },
  { texto: "Mas eu, pela tua grande misericórdia, entrarei na tua casa.", ref: "Salmos 5:7" },
  { texto: "Ele cura os que têm o coração quebrantado e lhes sara as feridas.", ref: "Salmos 147:3" },
  { texto: "Tudo o que pedirdes ao Pai em meu nome, ele vos concederá.", ref: "João 16:23" },
  { texto: "Porque não me envergonho do evangelho, pois é o poder de Deus para salvação.", ref: "Romanos 1:16" },
  { texto: "O Senhor teu Deus está no meio de ti, poderoso para salvar.", ref: "Sofonias 3:17" },
  { texto: "Não te lembres das coisas passadas, nem consideres as antigas. Eis que faço uma coisa nova.", ref: "Isaías 43:18-19" },
  { texto: "Eu te amo, ó Senhor, força minha.", ref: "Salmos 18:1" },
  { texto: "A minha graça é suficiente para ti, porque o meu poder se aperfeiçoa na fraqueza.", ref: "2 Coríntios 12:9" },
  { texto: "Felizes os misericordiosos, pois eles alcançarão misericórdia.", ref: "Mateus 5:7" },
  { texto: "Bom é render graças ao Senhor e cantar louvores ao teu nome, ó Altíssimo.", ref: "Salmos 92:1" },
  { texto: "Jesus lhe disse: Eu sou a ressurreição e a vida; quem crê em mim, ainda que morra, viverá.", ref: "João 11:25" },
  { texto: "Porque o Filho do Homem veio buscar e salvar o que se tinha perdido.", ref: "Lucas 19:10" },
  { texto: "O temor do Senhor é o começo da sabedoria.", ref: "Salmos 111:10" },
  { texto: "Mais vale um dia nos teus átrios do que mil em outro lugar.", ref: "Salmos 84:10" },
  { texto: "Eis que o olho do Senhor está sobre os que o temem, sobre os que esperam na sua misericórdia.", ref: "Salmos 33:18" },
  { texto: "E ele disse-me: a minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza.", ref: "2 Coríntios 12:9" },
  { texto: "Sede, pois, imitadores de Deus como filhos amados.", ref: "Efésios 5:1" },
  { texto: "Filho meu, dá-me o teu coração, e os teus olhos se agradem dos meus caminhos.", ref: "Provérbios 23:26" },
  { texto: "O Senhor te guardará na tua saída e na tua entrada, desde agora e para sempre.", ref: "Salmos 121:8" },
  { texto: "Qual é o homem que teme ao Senhor? A esse ele ensinará o caminho que deve escolher.", ref: "Salmos 25:12" },
  { texto: "Como a água fria para a alma cansada, assim são as boas notícias vindas de terra longínqua.", ref: "Provérbios 25:25" },
  { texto: "O Senhor está perto dos que têm o coração quebrantado e salva os de espírito abatido.", ref: "Salmos 34:18" },
  { texto: "Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá.", ref: "João 14:27" },
  { texto: "Toda boa dádiva e todo dom perfeito vêm do alto, descendo do Pai das luzes.", ref: "Tiago 1:17" },
  { texto: "O Senhor é justo em todos os seus caminhos e misericordioso em todas as suas obras.", ref: "Salmos 145:17" },
  { texto: "Porque eu sei que o meu Redentor vive.", ref: "Jó 19:25" },
  { texto: "A palavra da cruz é loucura para os que perecem, mas para nós que somos salvos é o poder de Deus.", ref: "1 Coríntios 1:18" },
  { texto: "Eis que venho depressa; e o meu galardão está comigo, para recompensar a cada um.", ref: "Apocalipse 22:12" },
  { texto: "Sede sóbrios e vigilantes. O diabo, vosso adversário, anda em derredor como leão que ruge.", ref: "1 Pedro 5:8" },
  { texto: "Porque todos os que são guiados pelo Espírito de Deus, esses são filhos de Deus.", ref: "Romanos 8:14" },
  { texto: "Cantai ao Senhor um cântico novo; cantai ao Senhor, toda a terra.", ref: "Salmos 96:1" },
  { texto: "E conhecereis a verdade, e a verdade vos libertará.", ref: "João 8:32" },
  { texto: "Bem-aventurado o povo cujo Deus é o Senhor.", ref: "Salmos 144:15" },
  { texto: "Porque tudo quanto é nascido de Deus vence o mundo.", ref: "1 João 5:4" },
  { texto: "A misericórdia do Senhor vai de eternidade até eternidade sobre os que o temem.", ref: "Salmos 103:17" },
  { texto: "Ora, o fim de tudo que se ouviu é isto: Teme a Deus e guarda os seus mandamentos.", ref: "Eclesiastes 12:13" },
  { texto: "O amor do Senhor enche a terra.", ref: "Salmos 33:5" },
  { texto: "Porque o Senhor dá a sabedoria; da sua boca é que vêm o conhecimento e o entendimento.", ref: "Provérbios 2:6" },
  { texto: "Que o amor fraternal permaneça.", ref: "Hebreus 13:1" },
  { texto: "Senhor, tu és o meu Deus; eu te exaltarei e louvarei o teu nome.", ref: "Isaías 25:1" },
  { texto: "Bem-aventurados os que têm fome e sede de justiça, porque eles serão fartos.", ref: "Mateus 5:6" },
  { texto: "Eu vim para que tenham vida, e a tenham em abundância.", ref: "João 10:10" },
  { texto: "Não seja covarde o teu coração, nem temas; não desmaies, nem te assombres.", ref: "Deuteronômio 31:8" },
  { texto: "Eis que faço novas todas as coisas.", ref: "Apocalipse 21:5" },
  { texto: "O Senhor, seu Deus, vai na frente de vocês e lutará a favor de vocês.", ref: "Deuteronômio 1:30" },
  { texto: "Mas os mansos herdarão a terra e se deleitarão em abundância de paz.", ref: "Salmos 37:11" },
  { texto: "Bem-aventurados os limpos de coração, porque eles verão a Deus.", ref: "Mateus 5:8" },
  { texto: "Portanto, tendo sido justificados pela fé, temos paz com Deus por nosso Senhor Jesus Cristo.", ref: "Romanos 5:1" },
  { texto: "A Deus seja a glória para todo o sempre! Amém.", ref: "Romanos 11:36" },
  { texto: "Sede, pois, misericordiosos, como também vosso Pai é misericordioso.", ref: "Lucas 6:36" },
  { texto: "Quem pode narrar os poderosos atos do Senhor? Quem pode proclamar todo o seu louvor?", ref: "Salmos 106:2" },
  { texto: "Bem-aventurado o homem que confia no Senhor e cuja esperança é o Senhor.", ref: "Jeremias 17:7" },
  { texto: "Nele vivemos, nos movemos e existimos.", ref: "Atos 17:28" },
  { texto: "Porque o Senhor teu Deus é Deus misericordioso; não te deixará, nem te destruirá.", ref: "Deuteronômio 4:31" },
  { texto: "Deus é o nosso refúgio e força, socorro bem presente na angústia.", ref: "Salmos 46:1" },
  { texto: "Mas quem beber da água que eu lhe darei nunca mais terá sede.", ref: "João 4:14" },
  { texto: "Todos nós, como ovelhas, andávamos desgarrados, cada um se desviava pelo seu caminho.", ref: "Isaías 53:6" },
  { texto: "Não me envergonho do evangelho, porque é o poder de Deus para salvação.", ref: "Romanos 1:16" },
  { texto: "Quem habita no amor habita em Deus, e Deus nele.", ref: "1 João 4:16" },
  { texto: "Alegrai-vos com os que se alegram; chorai com os que choram.", ref: "Romanos 12:15" },
  { texto: "Toda honra e glória ao Rei eterno, imortal, invisível, ao único Deus.", ref: "1 Timóteo 1:17" },
  { texto: "O nome do Senhor é uma torre forte; o justo corre a ela e está seguro.", ref: "Provérbios 18:10" },
  { texto: "Porque as misericórdias do Senhor não têm fim; as suas misericórdias não se esgotam.", ref: "Lamentações 3:22" },
  { texto: "Aquele que começou boa obra em vós a aperfeiçoará até ao Dia de Jesus Cristo.", ref: "Filipenses 1:6" },
  { texto: "O eterno Deus é o teu refúgio, e por baixo estão os braços eternos.", ref: "Deuteronômio 33:27" },
  { texto: "Jesus lhes disse: Eu sou o pão da vida; quem vem a mim nunca terá fome.", ref: "João 6:35" },
  { texto: "Com amor eterno eu te amei; por isso, com benignidade te atraí.", ref: "Jeremias 31:3" },
  { texto: "Quão preciosos me são, ó Deus, os teus pensamentos! Quão grande é a soma deles!", ref: "Salmos 139:17" },
  { texto: "Melhor é o fim das coisas do que o seu começo.", ref: "Eclesiastes 7:8" },
  { texto: "O Senhor abençoe a vocês e os proteja.", ref: "Números 6:24" },
  { texto: "Porque o Senhor ama a justiça e não abandona os seus santos.", ref: "Salmos 37:28" },
  { texto: "Aquele que crê no Filho tem a vida eterna.", ref: "João 3:36" },
  { texto: "Aproximai-vos de Deus, e ele se aproximará de vós.", ref: "Tiago 4:8" },
  { texto: "O Senhor é bom, um refúgio nos tempos de angústia; ele conhece os que nele confiam.", ref: "Naum 1:7" },
  { texto: "Louvai o Senhor todas as nações; celebrai-o todos os povos!", ref: "Salmos 117:1" },
  { texto: "Porque o amor de Cristo nos constrange.", ref: "2 Coríntios 5:14" },
  { texto: "Ele mesmo suportou os nossos pecados no seu corpo sobre o madeiro.", ref: "1 Pedro 2:24" },
  { texto: "Porque o Senhor, teu Deus, é Deus dos deuses e o Senhor dos senhores.", ref: "Deuteronômio 10:17" },
  { texto: "Graças a Deus pelo seu dom inefável!", ref: "2 Coríntios 9:15" },
  { texto: "Eis aqui o homem! Eis o teu Rei!", ref: "João 19:5,14" },
  { texto: "Em paz me deito e logo adormeço, porque só tu, Senhor, me fazes habitar em segurança.", ref: "Salmos 4:8" },
  { texto: "Não há nada impossível para Deus.", ref: "Lucas 1:37" },
  { texto: "Pois é pela graça que vocês foram salvos, por meio da fé.", ref: "Efésios 2:8" },
  { texto: "O Senhor lutará por vocês; basta que fiquem quietos.", ref: "Êxodo 14:14" },
  { texto: "Que a graça do Senhor Jesus Cristo esteja com o espírito de vocês.", ref: "Gálatas 6:18" },
  { texto: "Portanto, não desanimeis; porque ainda que o homem exterior se corrompa, o interior, contudo, se renova de dia em dia.", ref: "2 Coríntios 4:16" },
  { texto: "Sede, portanto, perfeitos como é perfeito o vosso Pai celestial.", ref: "Mateus 5:48" },
  { texto: "A misericórdia triunfa sobre o julgamento.", ref: "Tiago 2:13" },
  { texto: "Fazei tudo com amor.", ref: "1 Coríntios 16:14" },
  { texto: "O Senhor sustenta os humildes e derruba os ímpios por terra.", ref: "Salmos 147:6" },
  { texto: "Porque eu, o Senhor teu Deus, te sustento pela mão direita.", ref: "Isaías 41:13" },
  { texto: "Sede a luz do mundo.", ref: "Mateus 5:14" },
  { texto: "Ora, ao que pode fazer infinitamente mais do que tudo quanto pedimos ou pensamos, seja dada a glória.", ref: "Efésios 3:20" },
  { texto: "Porque o Senhor, teu Deus, é um Deus clemente; não te abandonará.", ref: "Deuteronômio 4:31" },
  { texto: "O Senhor reina; regozije-se a terra.", ref: "Salmos 97:1" },
  { texto: "Jesus Cristo, o mesmo ontem, hoje e eternamente.", ref: "Hebreus 13:8" },
  { texto: "A sua misericórdia é nova cada manhã; grande é a tua fidelidade!", ref: "Lamentações 3:23" },
  { texto: "O Senhor é cheio de graça e misericórdia, tardio em irar-se e de grande benevolência.", ref: "Salmos 145:8" },
  { texto: "Porque tão grande é o seu amor para com os que o temem como é a altura dos céus acima da terra.", ref: "Salmos 103:11" },
  { texto: "Não temas, porque eu te remi; chamei-te pelo teu nome; tu és meu.", ref: "Isaías 43:1" },
  { texto: "E o Senhor ia adiante deles, de dia numa coluna de nuvem, para os guiar no caminho.", ref: "Êxodo 13:21" },
  { texto: "Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, que nos abençoou com toda sorte de bênçãos espirituais.", ref: "Efésios 1:3" },
  { texto: "Neste mundo vocês terão aflições; contudo, tenham ânimo! Eu venci o mundo.", ref: "João 16:33" },
  { texto: "Clama a mim, e te responderei e te anunciarei grandes e ocultas coisas que não sabes.", ref: "Jeremias 33:3" },
  { texto: "E o fruto da justiça semeia-se em paz para os que praticam a paz.", ref: "Tiago 3:18" },
  { texto: "A nossa cidadania está nos céus, de onde também esperamos o Salvador.", ref: "Filipenses 3:20" },
  { texto: "Confiai nele em todo o tempo, ó povo; derramai perante ele o vosso coração.", ref: "Salmos 62:8" },
  { texto: "O amor perfeito lança fora o temor.", ref: "1 João 4:18" },
  { texto: "Mas, a todos quantos o receberam, deu-lhes o poder de serem feitos filhos de Deus.", ref: "João 1:12" },
  { texto: "Sede, pois, fortes no Senhor e na força do seu poder.", ref: "Efésios 6:10" },
  { texto: "Pois Deus tanto amou o mundo que deu o seu Filho unigênito.", ref: "João 3:16" },
  { texto: "Ensinai-me a fazer a tua vontade, pois tu és o meu Deus.", ref: "Salmos 143:10" },
  { texto: "Porque nenhum de nós vive para si mesmo, e nenhum morre para si mesmo.", ref: "Romanos 14:7" },
  { texto: "Bem-aventurado o povo que conhece a aclamação festiva; andará, ó Senhor, à luz do teu rosto.", ref: "Salmos 89:15" },
  { texto: "Sede cheios do Espírito Santo.", ref: "Efésios 5:18" },
  { texto: "Quando eu estava em angústia, invoquei o Senhor, e ele me respondeu.", ref: "Salmos 120:1" },
  { texto: "O Senhor tua rocha, tua fortaleza e teu libertador.", ref: "Salmos 18:2" },
  { texto: "Bem-aventurado o homem que persevera sob a provação.", ref: "Tiago 1:12" },
  { texto: "Porque a palavra de Deus é viva e eficaz.", ref: "Hebreus 4:12" },
  { texto: "A bênção do Senhor enriquece, e ele não acrescenta tristeza com ela.", ref: "Provérbios 10:22" },
  { texto: "E eu sou com vós todos os dias, até a consumação dos séculos.", ref: "Mateus 28:20" },
  { texto: "Não há nenhuma condenação para os que estão em Cristo Jesus.", ref: "Romanos 8:1" },
  { texto: "Amo o Senhor, porque ele ouviu a minha voz e as minhas súplicas.", ref: "Salmos 116:1" },
  { texto: "Que produz o amor, a alegria, a paz, a longanimidade, a benignidade, a bondade, a fidelidade, a mansidão.", ref: "Gálatas 5:22" },
  { texto: "Não andemos segundo a carne, mas segundo o Espírito.", ref: "Romanos 8:4" },
  { texto: "Porque a vossa vida está escondida com Cristo em Deus.", ref: "Colossenses 3:3" },
  { texto: "Cristo em vós, esperança da glória.", ref: "Colossenses 1:27" },
  { texto: "Mas eu, pela tua misericórdia, me alegrarei; o meu coração se exultará na tua salvação.", ref: "Salmos 13:5" },
  { texto: "Porque o Senhor é bom; a sua misericórdia dura para sempre.", ref: "Salmos 100:5" },
  { texto: "O Senhor me preserva de todo o mal; ele guarda a minha alma.", ref: "Salmos 121:7" },
  { texto: "Porque assim diz o Alto e o Sublime, que habita a eternidade: Habito no alto e no santo lugar, e também com o contrito e abatido de espírito.", ref: "Isaías 57:15" },
  { texto: "Por isso, não temais; mais valeis vós do que muitos pardais.", ref: "Mateus 10:31" },
  { texto: "E a paz de Deus, que excede todo entendimento, guardará os vossos corações e os vossos pensamentos.", ref: "Filipenses 4:7" },
  { texto: "O Senhor abriu os meus ouvidos, e eu não fui rebelde, nem me retirei para trás.", ref: "Isaías 50:5" },
  { texto: "Deus é amor, e quem permanece em amor permanece em Deus, e Deus nele.", ref: "1 João 4:16" },
  { texto: "Os que confiam no Senhor são como o monte Sião, que não se abala, mas permanece para sempre.", ref: "Salmos 125:1" },
  { texto: "Bendize, ó minha alma, ao Senhor!", ref: "Salmos 103:1" },
  { texto: "Porque sou eu que conheço os planos que tenho para vocês, diz o Senhor.", ref: "Jeremias 29:11" },
  { texto: "O Senhor é meu pastor e nada me faltará.", ref: "Salmos 23:1" },
  { texto: "Sede a luz do mundo. Uma cidade edificada sobre um monte não se pode esconder.", ref: "Mateus 5:14" },
  { texto: "E o meu Deus suprirá todas as vossas necessidades segundo as suas riquezas em glória.", ref: "Filipenses 4:19" },
  { texto: "Porque somos feitura dele, criados em Cristo Jesus para boas obras.", ref: "Efésios 2:10" },
  { texto: "E qualquer coisa que pedirdes em meu nome, eu o farei, para que o Pai seja glorificado no Filho.", ref: "João 14:13" },
  { texto: "Toda glória seja a Deus pelo seu dom inefável!", ref: "2 Coríntios 9:15" },
  { texto: "A graça do Senhor Jesus Cristo, o amor de Deus, e a comunhão do Espírito Santo sejam com todos vós.", ref: "2 Coríntios 13:14" },
  { texto: "Estou convencido de que aquele que começou boa obra em vós a completará.", ref: "Filipenses 1:6" },
  { texto: "Entrega o teu caminho ao Senhor; confia nele, e ele o fará.", ref: "Salmos 37:5" },
  { texto: "O Senhor é a minha luz e a minha salvação.", ref: "Salmos 27:1" },
  { texto: "Aguardai o Senhor; sede forte, e ele fortalecerá o vosso coração.", ref: "Salmos 27:14" },
  { texto: "Que cada um de vós ame a sua mulher como a si mesmo, e a mulher reverencie o marido.", ref: "Efésios 5:33" },
  { texto: "Mas os que esperam no Senhor renovarão as suas forças.", ref: "Isaías 40:31" },
  { texto: "Nisto consiste o amor: não em que nós tenhamos amado a Deus, mas em que ele nos amou.", ref: "1 João 4:10" },
  { texto: "Cantarei ao Senhor enquanto eu viver.", ref: "Salmos 104:33" },
  { texto: "Feliz o povo que tem o Senhor como seu Deus.", ref: "Salmos 144:15" },
  { texto: "A palavra do Senhor é reta, e todas as suas obras são fiéis.", ref: "Salmos 33:4" },
  { texto: "Venha o teu reino, seja feita a tua vontade, assim na terra como no céu.", ref: "Mateus 6:10" },
  { texto: "Porque em Cristo habitam corporalmente toda a plenitude da divindade.", ref: "Colossenses 2:9" },
  { texto: "Quem tem o Filho tem a vida.", ref: "1 João 5:12" },
  { texto: "Sejam fortes e corajosos. Não tenham medo, não se apavorem.", ref: "Deuteronômio 31:6" },
  { texto: "O Senhor lutará por vocês; basta que estejam quietos.", ref: "Êxodo 14:14" },
  { texto: "Portanto, não vos preocupeis com o amanhã.", ref: "Mateus 6:34" },
  { texto: "A palavra de Cristo habite em vós ricamente em toda a sabedoria.", ref: "Colossenses 3:16" },
  { texto: "Mas sede praticantes da palavra, e não somente ouvintes.", ref: "Tiago 1:22" },
  { texto: "Mas, se andarmos na luz, como ele está na luz, temos comunhão uns com os outros.", ref: "1 João 1:7" },
  { texto: "Louvai o Senhor, porque é bom louvar ao nosso Deus.", ref: "Salmos 147:1" },
  { texto: "Toda glória a Deus nas alturas e paz na terra para os homens.", ref: "Lucas 2:14" },
  { texto: "Grande é o teu amor, mais alto do que os céus; a tua fidelidade chega até as nuvens.", ref: "Salmos 108:4" },
  { texto: "Nós o amamos porque ele nos amou primeiro.", ref: "1 João 4:19" },
  { texto: "Sede gratos em todas as situações, pois esta é a vontade de Deus.", ref: "1 Tessalonicenses 5:18" },
  { texto: "Senhor, tu examinas e conheces tudo sobre mim.", ref: "Salmos 139:1" },
  { texto: "Quão grande é a tua bondade que reservaste para os que te temem!", ref: "Salmos 31:19" },
  { texto: "E a esperança não decepciona, porque o amor de Deus está derramado em nossos corações.", ref: "Romanos 5:5" },
  { texto: "Que todos te louvem, Senhor; que todos os reinos da terra te cantem!", ref: "Salmos 138:4" },
  { texto: "E o Deus de paz estará convosco.", ref: "Filipenses 4:9" },
  { texto: "Estas coisas vos tenho dito para que tenhais paz em mim.", ref: "João 16:33" },
];

// ── INICIALIZAR FIREBASE ADMIN ─────────────────────────────────────────
const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT);
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: process.env.FIREBASE_DATABASE_URL,
});
const db = admin.database();

// ── SELECIONAR VERSÍCULO DO DIA ────────────────────────────────────────
// Usa o dia do ano como índice para garantir que cada dia tem um versículo diferente
function getDiaDoAno() {
  const now = new Date();
  const inicio = new Date(now.getFullYear(), 0, 0);
  const diff = now - inicio;
  const umDia = 1000 * 60 * 60 * 24;
  return Math.floor(diff / umDia);
}

async function publicarVersiculo() {
  const dia = getDiaDoAno();
  const idx = (dia - 1) % VERSICULOS.length;
  const versiculo = VERSICULOS[idx];

  const dataFormatada = new Date().toLocaleDateString('pt-BR', {
    weekday: 'long', day: 'numeric', month: 'long',
    timeZone: 'America/Sao_Paulo'
  });

  // Capitalizar primeira letra do dia da semana
  const dataCapitalizada = dataFormatada.charAt(0).toUpperCase() + dataFormatada.slice(1);

  const texto = `📖 *Versículo do Dia* — ${dataCapitalizada}\n\n"${versiculo.texto}"\n\n— ${versiculo.ref}`;

  // Verificar se já foi publicado hoje (evita duplicatas se rodar duas vezes)
  const hoje = new Date().toISOString().slice(0, 10); // YYYY-MM-DD
  const checkRef = db.ref('versiculo_diario_controle');
  const snapshot = await checkRef.once('value');
  const ultimoPublicado = snapshot.val();

  if (ultimoPublicado === hoje) {
    console.log(`✓ Versículo de ${hoje} já foi publicado hoje. Pulando.`);
    process.exit(0);
  }

  // Publicar no feed como post do "sistema"
  const postsRef = db.ref('posts');
  await postsRef.push({
    texto,
    foto: null,
    autorUid: 'sistema',
    autorNome: '🦫 Nossa Família',
    autorFoto: null,
    ts: Date.now(),
    isVersiculo: true,
  });

  // Registrar que já publicou hoje
  await checkRef.set(hoje);

  console.log(`✅ Versículo publicado com sucesso!`);
  console.log(`📖 ${versiculo.ref}: "${versiculo.texto.slice(0, 60)}..."`);
  process.exit(0);
}

publicarVersiculo().catch(err => {
  console.error('❌ Erro ao publicar versículo:', err);
  process.exit(1);
});
